WordPress/wp-movies-demo

wp-movies-theme/functions.php, wp-movies-theme/parts/header.html
This adds a post of type `wp_navigation` on the initial load. This post is used in the Navigation block in the header of the theme to add a list of links to `Movies` and `Actors` pages.
=> Add the navigation post and use it in the header

.wp-env.json, README.md
=> Update the README

wp-movies-theme/functions.php
The title says it all. `get_page_by_title()` is [deprecated](https://core.trac.wordpress.org/ticket/57041) in WordPress 6.2.
=> Replace deprecated `get_page_by_title()` with `WP_Query()`

src/blocks/favorites-number/view.js, src/blocks/post-favorite/view.js, webpack.config.js, wpmovies.php
⚠️ **Stacked PR (note the PR base)**
The `view.js` file for the `favorites-number` block contains the actions and state that are also used by the `post-favorites` block.
I've added a new `view.js` file for the `post-favorites` block that includes the references to the state and actions used in that block's `render.php`.
This way, the actions, state and selectors are defined within the same block and there's a better separation of concerns.
=> Move the state, actions & selectors used by a block to that blocks' `view.js` file

src/blocks/movie-trailer-button/block.json
I'm adding the `interactivity: true` to the `movie-trailer-button` blocks. Although it doesn't have a store, it is using some directives.
This solves the issue of the Trailer not playing when client-side navigations are disabled.
=> Add `interactivity: true` to movie-trailer-button block

lib/custom-query-block.php
Adding a key makes Preact treat each item as a separate thing and fixes the weird UX of previous images staying on the screen when you paginate.
It should probably be done at the `<img>` level by default in Gutenberg, using the image database ID for the key. Here I did it in the `<li>` just for convenience.
Before (using Slow 3G):
https://user-images.githubusercontent.com/3305402/225347063-ca1cbfe5-04e8-4a4a-9499-040d75d5ceb1.mp4
---
After (using Slow 3G):
https://user-images.githubusercontent.com/3305402/225347224-528384eb-00fc-4bfb-a645-86c76bdee2c5.mp4
=> Add key attribute to each Query Loop item

wpmovies.php
To make things easier to analyze, the site should only enqueue the code of the Interactivity API. This PR just removes the emoji enqueues.
Before:
After:
---
We may need to add other removals for the live site at WP.com.
=> Remove frontend emoji enqueue

wpmovies.php
This fixes an accessibility issue with the SPA search. When you use a screen reader like Voice over and use the search you previously got no indication that the search results were updating. 
Ideally this would also use a directive to get the number of results found. 
I also tried to add some content to the "No Results" block in the query and with the client site navigation this never gets rendered 🤔
=> Fix: add aria-live region to query block so that the live updating results are announced to screen readers

src/blocks/interactive/likes-number/block.json, src/blocks/interactive/movie-like-button/block.json, src/blocks/interactive/movie-like-icon/block.json, src/blocks/interactive/movie-search/block.json, src/blocks/interactive/movie-tabs/block.json, src/blocks/interactive/video-player/block.json, webpack.config.js, wpmovies.php
In the current iteration there are a few manual steps that need to be done in order for an interactive block to work correctly that are not how these blocks will work in the future. This PR updates the flow so that all these steps get handled automatically by the plugin instead of manually by the block author.
This PR updates it so that any block that has `supports.interactivity` set to true will automatically get the `wp-directive-runtime` script dependency added to any `viewScript` scripts. 
Additionally it also auto registers all the blocks. So when you add a new block you don't need to touch any files outside of the blocks folder itself.
=> fix clean up registration of blocks

src/blocks/interactive/likes-number/render.php, src/blocks/interactive/movie-genres/render.php, src/blocks/interactive/movie-like-button/render.php, src/blocks/interactive/movie-like-icon/render.php, src/blocks/interactive/movie-search/render.php, src/blocks/interactive/movie-tabs/render.php, src/blocks/interactive/movie-trailer-button/render.php, src/blocks/interactive/video-player/render.php
EDIT: ~~Note: Right now, the `wp-text` directive breaks the page until [this](https://github.com/WordPress/block-interactivity-experiments/pull/188) is solved.~~ Merged now
Based on the decisions made here https://github.com/WordPress/block-interactivity-experiments/issues/132#issuecomment-1466738441, we changed the format of the directives (https://github.com/WordPress/block-interactivity-experiments/pull/181 & https://github.com/WordPress/block-interactivity-experiments/pull/184).
I'm opening this pull request to adapt the movies demo's code to that format and make it work with the latest version of the block-interactivity-experiments.
=> Change directives to new format "data-wp-directive.event`

docs/interactive-blocks/README.md, src/blocks/interactive/likes-number/render.php, src/blocks/interactive/movie-like-button/render.php, src/blocks/interactive/movie-like-icon/render.php, src/blocks/interactive/movie-search/render.php, src/blocks/interactive/movie-tabs/render.php, src/blocks/interactive/video-player/render.php
⚠️ _Don't merge until [this pull request](https://github.com/WordPress/block-interactivity-experiments/pull/190) from the block-interactivity-experiments repo is merged._
As decided [here](https://github.com/WordPress/block-interactivity-experiments/issues/136#issuecomment-1463944790), the Interactivity API will use `wp_store()` instead of `store()` for the PHP files. Once [this pull request to make that change](https://github.com/WordPress/block-interactivity-experiments/pull/190) is merged, we need to modify the blocks code to use `wp_store()`.
=> Rename `store` to `wp_store` in PHP files

src/blocks/interactive/movie-search/render.php
With the browser autocomplete I get those weird autocompletions that are not appropriate for the Search block:
=> Disable the browser autocompletion

wp-movies-theme/parts/footer.html
Added the "Code for this demo is [on GitHub](https://github.com/WordPress/wp-movies-demo/)"
=> Add a link to the WP movies repo in footer

docs/interactive-blocks/README.md, src/blocks/interactive/likes-number/render.php, src/blocks/interactive/movie-like-button/render.php, src/blocks/interactive/movie-like-icon/render.php, src/blocks/interactive/movie-search/render.php, src/blocks/interactive/movie-tabs/render.php, src/blocks/interactive/movie-trailer-button/render.php, src/blocks/interactive/video-player/render.php
I updated the current blocks to match [the changes made in the Block Interactivity Experiments repo](https://github.com/WordPress/block-interactivity-experiments/pull/239).
In the Block Interactivity Experiments repo, these changes were made because:
1. JSX doesn't support attributes with dots in them.
2. The term island has no meaning in WordPress, and we don't intend to embrace it.
* Change the directives to use `data-wp-on--` instead of the dot.
=> Change directives suffix to double hyphen instead of dot

README.md
I noticed some room for improvement in the README.
The installation steps were not clearly separated for people who **are** using `wp-env` vs. the ones that are not.
=> Update README.md with better setup instructions.

README.md
This repo doesn't work anymore until we migrate it to use the Interactivity API version shipped in Gutenberg, so I've added a warning in the Readme.
Fixes https://github.com/WordPress/wp-movies-demo/issues/55.
=> Warn people to use the Getting Started guide instead of this repo

wpmovies.php
Even though there is actually a comment in the code saying we check if Gutenberg is installed, we are not really doing it. This pull request adds that check and triggers an admin notice when Gutenberg is deactivated.
=> Deactivate plugin when Gutenberg is not installed and activated

README.md, docs/interactive-blocks/README.md, package-lock.json, package.json, src/blocks/interactive/likes-number/block.json, src/blocks/interactive/likes-number/render.php, src/blocks/interactive/likes-number/view.js, src/blocks/interactive/movie-genres/render.php, src/blocks/interactive/movie-like-button/render.php, src/blocks/interactive/movie-like-button/view.js, src/blocks/interactive/movie-like-icon/view.js, src/blocks/interactive/movie-search/render.php, src/blocks/interactive/movie-search/view.js, src/blocks/interactive/movie-tabs/view.js, src/blocks/interactive/movie-trailer-button/render.php, src/blocks/interactive/video-player/render.php, src/blocks/interactive/video-player/view.js
I've been looking through the code and have improved a few things. I have also improved the README files.
Some things were still outdated and did not correspond to how the Interactivity API works in its latest version. Other things are simply improvements.
I explained the changes in the comments below.
=> Improve code and docs

src/blocks/interactive/movie-search/style.css
Found through a linter when using this file in a different project.
Per the CSS spec, if a rule is duplicated, it's the last occurrence that's applied, so I'm removing the first one.
=> style.css: Remove duplicate border property

docs/interactive-blocks/README.md, lib/custom-query-block.php, lib/db-update/index.php, lib/db-update/update-xml.php, src/blocks/interactive/movie-tabs/render.php, src/blocks/interactive/movie-trailer-button/render.php, src/blocks/non-interactive/actor-birth-place/render.php, src/blocks/non-interactive/actor-birthday/render.php, src/blocks/non-interactive/movie-data/render.php, src/blocks/non-interactive/movie-release-date/render.php, src/blocks/non-interactive/movie-runtime/render.php, src/blocks/non-interactive/movie-score/render.php, src/blocks/non-interactive/page-background/render.php, wp_sampledata_actors.xml, wp_sampledata_media.xml, wp_sampledata_movies.xml
Following #72. Let's unprotect the meta fields so we can use the post-meta binding to display most of the movies and actors data.
`wpmovies_recommended`, `wpmovies_similar` or `wpmovies_videos` could be still private, but let's leave them public just in case.
=> Unprotect all movies and actors meta fields.

src/blocks/interactive/movie-trailer-button/render.php, src/blocks/non-interactive/movie-score/render.php
Due to cache issues on the site db. We had a couple of fatals while trying to do `array_filter` over a null value.
This quick PR prevents those.
Many custom blocks like these will be soon moved to block bindings.
=> Prevent fatals if post_meta is null.
